services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.0.0
    container_name: mlflow-replay
    ports:
      - "8000:8000"
    volumes:
      - /mnt/public-metrics:/mlflow/metrics:
      - /mnt/public-artifacts:/mlflow/artifacts:
    command:
      - mlflow
      - server
      - --backend-store-uri=/mlflow/metrics
      - --default-artifact=/mlflow/artifacts
      - --serve-artifacts
      - --host=0.0.0.0
      - --port=8000