services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow-replay
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - /mnt/public-metrics:/mlflow/metrics
    environment:
      - MLFLOW_S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - AWS_REQUEST_CHECKSUM_CALCULATION=WHEN_REQUIRED
      - GUNICORN_CMD_ARGS=--timeout 300
      - AWS_RESPONSE_CHECKSUM_VALIDATION=WHEN_REQUIRED
    command:
      - mlflow
      - server
      - --backend-store-uri=/mlflow/metrics
      - --artifacts-destination=s3://${CONTAINER_NAME}
      - --serve-artifacts
      - --host=0.0.0.0
      - --port=8000