services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.0.0
    container_name: mlflow-replay
    ports:
      - "8000:8000"
    volumes:
      - /mnt/public-metrics:/mlflow/metrics:rw
      - /mnt/public-artifacts:/mlflow/artifacts:rw
    environment:
      - MLFLOW_S3_ENDPOINT_URL=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_REQUEST_CHECKSUM_CALCULATION=WHEN_REQUIRED
      - AWS_RESPONSE_CHECKSUM_VALIDATION=WHEN_REQUIRED  
    command:
      - mlflow
      - server
      - --backend-store-uri=/mlflow/metrics
      - --default-artifact-root=
      - --serve-artifacts
      - --host=0.0.0.0
      - --port=8000